name: Test and Deploy CDK

on:
  workflow_dispatch:
  push:
    paths:
      - 'Backend/**'


jobs:
  static-analysis:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            Backend/requirements.txt
            Backend/requirements-dev.txt

      - name: Install Dependencies
        run: |
          pip install -r Backend/requirements.txt
          pip install -r Backend/requirements-dev.txt
        
      - name: Create Results Directory
        run: mkdir -p results/static-analysis

      - name: Run Flake8 (Linting)
        run: flake8 Backend/lambda_functions --count --statistics --color never --output-file results/flake8.txt --exit-zero

      - name: Run Mypy (Type Checking)
        run: mypy Backend/lambda_functions > results/mypy.txt || true

      - name: Run Bandit (Security Scan)
        run: bandit -r Backend/lambda_functions -f json -o results/bandit.json

      - name: Upload Static Analysis Results
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis
          path: results/

        

  

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            Backend/requirements.txt
            Backend/requirements-dev.txt

      - name: Install Dependencies
        run: |
          pip install -r Backend/requirements.txt
          pip install -r Backend/requirements-dev.txt

      - name: Create .env file from GitHub secret
        run: echo "${{ secrets.ENV_FILE }}" > Backend/tests/.env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Create Results Directory
        run: mkdir results

      - name: Run Unit Tests
        run: pytest Backend/tests/unit --junitxml=results/unit-results.xml --cov=Backend/tests/unit --cov-report=xml:results/unit-coverage/coverage.xml --cov-report=html:results/unit-coverage --benchmark-compare --benchmark-json=results/unit-benchmark-results.json

      - name: Upload Unit Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-results
          path: results/unit-results.xml

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-benchmark-results
          path: results/unit-benchmark-results.json

      - name: Upload Unit Coverage
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: results/unit-coverage


  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            Backend/requirements.txt
            Backend/requirements-dev.txt

      - name: Install Dependencies
        run: |
          pip install -r Backend/requirements.txt
          pip install -r Backend/requirements-dev.txt

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create .env file from GitHub secret
        run: echo "${{ secrets.ENV_FILE }}" > Backend/tests/.env

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Synthesize CDK
        run: |
          cd Backend/cdk
          cdk synth

      - name: Run Local API with SAM
        run: | 
          cd Backend/cdk
          sam local start-api -t cdk.out/CdkStack.template.json/ &
          sleep 10
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2

      - name: Run Integration Tests
        run: |
          pytest Backend/tests/integration --junitxml=results/integration-results.xml --cov=Backend/tests/integration --cov-report=xml:results/integration-coverage/coverage.xml --cov-report=html:results/integration-coverage

      - name: Upload Integration Results
        uses: actions/upload-artifact@v4
        with:
          name: integration-results
          path: results/
        
      - name: Upload Integration Coverage
        uses: actions/upload-artifact@v4
        with:
          name: integration-coverage
          path: results/integration-coverage

  cdk-tests:
    name: Run CDK Tests
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            Backend/requirements.txt
            Backend/requirements-dev.txt

      - name: Install Dependencies
        run: |
          pip install -r Backend/requirements.txt
          pip install -r Backend/requirements-dev.txt

      - name: Run CDK Tests
        run: |
          pytest Backend/cdk/tests --junitxml=results/cdk-results.xml --cov=Backend/cdk --cov-report=xml:results/cdk-coverage/coverage.xml --cov-report=html:results/cdk-coverage

      - name: Upload CDK Test Results
        uses: actions/upload-artifact@v4
        with:
          name: cdk-results
          path: results/cdk-results.xml

      - name: Upload CDK Coverage
        uses: actions/upload-artifact@v4
        with:
          name: cdk-coverage
          path: results/cdk-coverage

  deploy:
    name: Deploy CDK
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, cdk-tests]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            Backend/requirements.txt
            Backend/requirements-dev.txt

      - name: Install Dependencies
        run: |
          pip install -r Backend/requirements.txt
          pip install -r Backend/requirements-dev.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy CDK Stack
        run: |
          mkdir results
          cd Backend/cdk
          cdk deploy --require-approval never 2>&1 | tee ../../results/cdk-deploy.log
        shell: bash

      
      
      - name: Upload CDK Log
        uses: actions/upload-artifact@v4
        with:
          name: cdk-deploy
          path: results/cdk-deploy.log

  e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            Backend/requirements.txt
            Backend/requirements-dev.txt

      - name: Install Dependencies
        run: |
          pip install -r Backend/requirements.txt
          pip install -r Backend/requirements-dev.txt

      - name: Create .env file from GitHub secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Run E2E Tests
        run: |
          pytest Backend/tests/e2e --junitxml=results/e2e-results.xml --cov=Backend/tests/e2e --cov-report=xml:results/e2e-coverage/coverage.xml --cov-report=html:results/e2e-coverage

      - name: Upload Integration Results
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results
          path: results/

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: e2e-coverage
          path: results/e2e-coverage


   
  report:
    name: Generate and Upload Report
    runs-on: ubuntu-latest
    needs: [unit-tests,integration-tests, cdk-tests, e2e]
    if: always()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          path: results

      - name: Create Report
        run: |
          python Backend/scripts/generate_workflow_report.py
          cat results/workflow-report.md >> $GITHUB_STEP_SUMMARY

      - name: Upload Report File
        uses: actions/upload-artifact@v4
        with:
          name: workflow-report
          path: results/workflow-report.md
